import Head from "next/head";
import Image from "next/image";
import {
  Banner,
  Exercises,
  Offers,
  Showcase,
  AccordionList,
} from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fitness App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/exercise.png" />
      </Head>
      <main className="py-10, bg-black">
        <Banner />
        <Exercises />
        <Offers />
        <Showcase />
        <AccordionList />
      </main>
    </>
  );
}
